project:
  type: website
  output-dir: docs

execute:
  freeze: true

website:
  title: "Tzu-Yao Lin"
  site-url: https://tzuyao-lin.github.io/
  description: "Research, statistics, and R by Tzu-Yao Lin"
  #google-analytics: ""
  navbar:
    left:
      - href: about.qmd
        text: "About Me"
      - href: blog.qmd
        text: "Posts"
      - href: publication.qmd
        text: "Publications"
    right:
      - icon: github
        href: https://github.com/tzuyao-lin
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: source
