project:
  type: website
  output-dir: docs

execute:
  freeze: true

website:
  title: "Tzu-Yao Lin"
  site-url: https://xup6y3ul6.github.io/tzuyaolin_blog/
  description: "Research, statistics, and R by Tzu-Yao Lin"
  #google-analytics: ""
  navbar:
    left:
      - href: blog.qmd
        text: "Posts"
      - href: research/publication.qmd
        text: "Publications"
    right:
      - icon: github
        href: https://github.com/xup6y3ul6
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: source
