{
  "hash": "a25cf6ef62b71615f58c28bdf663508a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analysis Notes on Coffee Consumption, Polygenic Risk Score, and Diabetes\"\nauthor: \"Tzu-Yao Lin\"\ndate: 2024-09-18\ndate-modified: 2026-09-01\ndescription: \"A public record of analyses conducted during the preparation of a collaborative study using data from The Maastricht Study.\"\ncategories:\n - \"r\"\n - \"statistics\"\n - \"research notes\"\nimage: CDP.png\nexecute:\n  warning: false\n  freeze: true\nformat: \n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    self-contained: true\n    code-fold: true\n    code-tools: true\n---\n\n::: callout-note\n## About this analysis record\n\nThis page documents analyses conducted during the preparation of a collaborative study of coffee consumption, polygenic risk score, and diabetes using data from The Maastricht Study. It is retained as a public record of the analytical workflow and is not intended as a complete tutorial or as the definitive report of the study.\n\nThe final methods, results, and interpretations are reported in [Rao et al. (2025), *Interaction between coffee consumption and polygenic risk score in relation to diabetes: insights from the Maastricht study*](https://doi.org/10.1007/s00394-025-03782-y).\n:::\n\n# Purpose and analytical scope\n\nThis record arose while checking and developing the statistical analyses for a collaborative cross-sectional study using data from The Maastricht Study. The outcome distinguished participants with normal glucose metabolism (NGM), prediabetes, and type 2 diabetes mellitus (T2DM). The main exposures were habitual coffee consumption and a polygenic risk score (PRS) for T2DM.\n\nThe scientific questions were whether coffee consumption and PRS were separately associated with the prevalence of prediabetes and T2DM, and whether the association between PRS and glucose-metabolism status differed across levels of coffee consumption. Because these analyses use cross-sectional observational data, the estimates describe associations with prevalent glucose-metabolism categories; they do not by themselves establish causal or preventive effects.\n\n## Questions documented in this record\n\nThe working analysis focused on five practical questions that arose during manuscript preparation:\n\n1. How should missing observations be handled so that candidate models are fitted to comparable data?\n2. Is an ordinal logistic model appropriate for the three glucose-metabolism categories?\n3. If the proportional-odds assumption is not tenable, should the outcome be analyzed using two binary logistic regressions or one multinomial logistic regression?\n4. How do estimates for coffee consumption and PRS change across the proposed covariate sets?\n5. How should the coffee-by-PRS interaction and odds ratios for joint exposure categories be evaluated and presented?\n\nThis page concentrates on these model-development questions and the construction of working result tables. It does not document every analysis reported in the published article. In particular, the published study also reports dose-response and sensitivity analyses that are outside the scope of this record. Some sections below preserve working questions, intermediate comparisons, and decisions that differ from the final publication.\n\n# Data availability and privacy\n\nThe participant-level dataset used for this analysis is restricted and is not distributed with this public website repository. The file contains individual-level health, demographic, behavioral, medication, socioeconomic, and polygenic-risk variables. Whether any subset may be shared depends on the original consent, data-use agreement, ethics approval, and applicable institutional requirements; repository publication should not be assumed to be permitted.\n\nFor local reproduction by an authorized researcher, the dataset must be stored outside the repository and supplied through the `CDP_DATA_PATH` environment variable. The analysis rejects paths inside the website project. Public outputs should contain aggregate summaries and model results rather than participant-level records.\n\n# Data preprocessing\n\nThe restricted dataset used below was supplied as a preprocessed analysis file through `CDP_DATA_PATH`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(nnet)\nlibrary(epiDisplay)\nlibrary(lmtest)\nlibrary(gt)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_path <- Sys.getenv(\"CDP_DATA_PATH\")\n\nif (!nzchar(data_path)) {\n  stop(\"Set CDP_DATA_PATH to the restricted dataset outside this project.\")\n}\n\ndata_path <- normalizePath(data_path, mustWork = TRUE)\nproject_dir <- Sys.getenv(\n  \"QUARTO_PROJECT_DIR\",\n  unset = normalizePath(\"../..\", mustWork = TRUE)\n)\nproject_dir <- normalizePath(project_dir, mustWork = TRUE)\n\nif (\n  identical(data_path, project_dir) ||\n    startsWith(data_path, paste0(project_dir, .Platform$file.sep))\n) {\n  stop(\"CDP_DATA_PATH must point outside the public website project.\")\n}\n\nanalysis_variables <- c(\n  \"N_Diabetes_WHO\", \"N_DIABETES_2b\", \"PRS_tertiles\",\n  \"coffee_tertiles\", \"SEX\", \"Age\", \"bmi\", \"NIT_alcoholtot\",\n  \"smoking_3cat\", \"mean_step_min_wake_T\", \"DHD_sum\", \"NIT_kcal\",\n  \"N_CVD\", \"Tot_chol\", \"N_OMAP\", \"med_HT\", \"med_LP\",\n  \"FIT_suikerg\", \"B1_VD1_2.6.29\", \"N_Education_3cat\"\n)\n\ndata <- read_csv(\n  data_path,\n  na = c(\"\", \"NA\", \"-999\", \"-888\"),\n  col_select = all_of(analysis_variables)\n)\n```\n:::\n\n\nOnly variables needed for the working analyses below are loaded. Public outputs should contain aggregate summaries and model results rather than participant-level records.\n\nThe variables required for the candidate outcome, exposure, and covariate specifications are then recoded for analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes_with_na <- data |>\n    mutate(Diabetes = factor(N_Diabetes_WHO, labels = c(\"NGM\", \"Pre\", \"T2DM\"), ordered = TRUE),\n           IsDiabetes = factor(N_DIABETES_2b),\n           PRS = factor(PRS_tertiles, labels = c(\"Low\", \"Medium\", \"High\")), \n           Coffee = factor(coffee_tertiles, labels = c(\"Low\", \"Medium\", \"High\")),\n           Sex = factor(SEX, labels = c(\"Male\", \"Female\")),\n           Age = Age,\n           BMI = bmi,\n           Alcohol = NIT_alcoholtot,\n           Smoking = factor(smoking_3cat, labels = c(\"Never\", \"Former\", \"Current\")),\n           Step_wake = mean_step_min_wake_T,\n           DHD = DHD_sum, \n           KCal = NIT_kcal, \n           CVD = factor(N_CVD, labels = c(\"No\", \"Yes\")),\n           Chol = Tot_chol,\n           # HT = factor(N_HT, labels = c(\"No\", \"Yes\")),\n           OMAP = N_OMAP,\n           Med_HT = factor(med_HT, labels = c(\"No\", \"Yes\")),\n           Med_LP = factor(med_LP, labels = c(\"No\", \"Yes\")),\n           Sugar = FIT_suikerg,\n           B1_VD1 = factor(B1_VD1_2.6.29, labels = c(\"Yes\", \"No\", \"Unknow\")),\n           Education = factor(N_Education_3cat, labels = c(\"Low\", \"Medium\", \"High\")),\n           .keep = \"none\") \n\nskimr::skim(diabetes_with_na)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |                 |\n|:------------------------|:----------------|\n|Name                     |diabetes_with_na |\n|Number of rows           |7668             |\n|Number of columns        |20               |\n|_______________________  |                 |\n|Column type frequency:   |                 |\n|factor                   |11               |\n|numeric                  |9                |\n|________________________ |                 |\n|Group variables          |None             |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                      |\n|:-------------|---------:|-------------:|:-------|--------:|:-------------------------------|\n|Diabetes      |         0|          1.00|TRUE    |        3|NGM: 4868, T2D: 1641, Pre: 1159 |\n|IsDiabetes    |         0|          1.00|FALSE   |        2|0: 6027, 1: 1641                |\n|PRS           |         0|          1.00|FALSE   |        3|Med: 2561, Low: 2556, Hig: 2551 |\n|Coffee        |         0|          1.00|FALSE   |        3|Low: 2949, Med: 2369, Hig: 2350 |\n|Sex           |         0|          1.00|FALSE   |        2|Fem: 3858, Mal: 3810            |\n|Smoking       |        56|          0.99|FALSE   |        3|For: 3764, Nev: 2911, Cur: 937  |\n|CVD           |        86|          0.99|FALSE   |        2|No: 6342, Yes: 1240             |\n|Med_HT        |         7|          1.00|FALSE   |        2|No: 4904, Yes: 2757             |\n|Med_LP        |         7|          1.00|FALSE   |        2|No: 5390, Yes: 2271             |\n|B1_VD1        |        97|          0.99|FALSE   |        3|No: 4082, Yes: 2417, Unk: 1072  |\n|Education     |       100|          0.99|FALSE   |        3|Hig: 2984, Low: 2511, Med: 2073 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|    mean|     sd|     p0|     p25|     p50|     p75|    p100|hist  |\n|:-------------|---------:|-------------:|-------:|------:|------:|-------:|-------:|-------:|-------:|:-----|\n|Age           |         0|          1.00|   59.93|   8.64|  39.00|   54.00|   61.00|   67.00|   79.00|▃▅▇▇▂ |\n|BMI           |         2|          1.00|   26.80|   4.41|  14.40|   23.80|   26.20|   29.10|   56.30|▂▇▂▁▁ |\n|Alcohol       |         0|          1.00|   11.82|  13.35|   0.00|    1.60|    8.10|   18.01|  197.53|▇▁▁▁▁ |\n|Step_wake     |      1295|          0.83|  118.91|  40.26|   5.14|   90.72|  116.32|  144.69|  314.36|▁▇▅▁▁ |\n|DHD           |         0|          1.00|   84.02|  15.26|  10.76|   73.60|   84.30|   94.91|  131.17|▁▁▇▇▁ |\n|KCal          |         0|          1.00| 2121.23| 603.92| 594.18| 1691.53| 2048.51| 2491.85| 4178.56|▁▇▇▂▁ |\n|Chol          |         1|          1.00|    5.22|   1.10|   2.10|    4.40|    5.20|    6.00|   10.40|▂▇▆▁▁ |\n|OMAP          |         5|          1.00|   94.70|  11.38|  61.00|   87.00|   94.00|  102.00|  145.00|▁▇▇▁▁ |\n|Sugar         |         0|          1.00|    2.62|   7.22|   0.00|    0.00|    0.00|    2.15|  120.00|▇▁▁▁▁ |\n\n\n:::\n:::\n\n\nMissingness was not evenly distributed across the selected variables. In particular, `Step_wake` had more than 1,000 missing observations, so requiring complete data on all 20 variables substantially reduced the analysis sample.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiabetes <- diabetes_with_na |> drop_na()\n\ntibble(\n  complete_cases = nrow(diabetes),\n  excluded_rows = nrow(diabetes_with_na) - nrow(diabetes)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  complete_cases excluded_rows\n           <int>         <int>\n1           6224          1444\n```\n\n\n:::\n:::\n\n\n::: callout-warning\n## Working decision: complete-case dataset\n\nAt this stage of the analysis, the treatment of missing observations in the source preprocessing was not fully documented. For the model comparisons below, I constructed one complete-case dataset by excluding any participant with `NA`, `-999`, or `-888` on at least one of the 20 selected variables.\n\nUsing a common analysis sample ensured that differences in AIC or likelihood-ratio tests across the candidate models were not caused by fitting the models to different sets of participants. This produced a working sample of 6,224 complete cases after excluding 1,444 rows. By comparison, the published article reports an included study sample of 7,668 and labels its main association table as $n = 7{,}668$. This record does not establish how the difference between that reporting and the complete-case workflow shown here was resolved.\n\nComplete-case analysis was a working decision for comparability, not a general recommendation that it is optimal. The substantial missingness in `Step_wake` may affect precision and the population represented by the fitted models, and this page does not include a missing-data sensitivity analysis.\n:::\n\n::: callout-important\n## Open questions recorded during analysis\n\nThe following questions were recorded before the manuscript decisions were finalized:\n\n1. What was the substantive reason for categorizing PRS and coffee consumption into low, medium, and high groups rather than retaining continuous measures? If tertiles were retained, should an additional trend or dose-response analysis be reported?\n\n2. What interpretive advantage did tertiles provide, and how should their simpler presentation be weighed against the loss of information caused by categorization?\n\nThe published study subsequently described both variables as study-population tertiles and additionally examined coffee consumption using a continuous dose-response analysis. The final article should therefore be used for the definitive rationale and specification.\n:::\n\n# Model development record\n\n## Outcome-model choice\n\nThe outcome categories---NGM, prediabetes, and T2DM---have a clinical ordering, so an ordinal logistic model was considered first. A proportional-odds model assumes that each predictor has the same coefficient across the cumulative comparisons induced by the ordered outcome. This restriction was checked using the Brant test.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nolm <- MASS::polr(Diabetes ~ PRS + Coffee + Age + Sex + BMI + Alcohol + Smoking + Step_wake + DHD + KCal + CVD + Chol + OMAP + Med_HT + Med_LP + Sugar + B1_VD1 + Education, data = diabetes, Hess = TRUE)\nbrant::brant(olm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n---------------------------------------------------- \nTest for\t\tX2\tdf\tprobability \n---------------------------------------------------- \nOmnibus\t\t\t208.92\t23\t0\nPRSMedium\t\t4.41\t1\t0.04\nPRSHigh\t\t\t6.4\t1\t0.01\nCoffeeMedium\t\t0.86\t1\t0.36\nCoffeeHigh\t\t0.25\t1\t0.62\nAge\t\t\t6.87\t1\t0.01\nSexFemale\t\t7.62\t1\t0.01\nBMI\t\t\t0.21\t1\t0.65\nAlcohol\t\t\t5.78\t1\t0.02\nSmokingFormer\t\t0.58\t1\t0.45\nSmokingCurrent\t\t1.04\t1\t0.31\nStep_wake\t\t5.9\t1\t0.02\nDHD\t\t\t1.88\t1\t0.17\nKCal\t\t\t0.95\t1\t0.33\nCVDYes\t\t\t1.21\t1\t0.27\nChol\t\t\t57.18\t1\t0\nOMAP\t\t\t0.24\t1\t0.62\nMed_HTYes\t\t0.4\t1\t0.53\nMed_LPYes\t\t4.93\t1\t0.03\nSugar\t\t\t9.85\t1\t0\nB1_VD1No\t\t29.36\t1\t0\nB1_VD1Unknow\t\t4.06\t1\t0.04\nEducationMedium\t0.96\t1\t0.33\nEducationHigh\t\t0.52\t1\t0.47\n---------------------------------------------------- \n\nH0: Parallel Regression Assumption holds\n```\n\n\n:::\n:::\n\n\nThe omnibus Brant test rejected the proportional-odds assumption for this model ($\\chi^2 = 208.92$, $df = 23$, $p < .001$). Several predictor-specific tests also indicated nonproportionality. The proportional-odds specification was therefore not retained for the working analyses below.\n\n::: callout-note\n## Working decision: baseline-category multinomial model\n\nAt this stage, a baseline-category multinomial logistic model was adopted with NGM as the reference outcome. This allowed the association of each predictor with prediabetes versus NGM to differ from its association with T2DM versus NGM.\n:::\n\nFor outcome category $j \\in \\{\\text{Pre}, \\text{T2DM}\\}$, the baseline-category logit can be written as\n\n$$\n\\eta_j(\\mathbf{x})\n= \\log\\left(\\frac{p_j}{p_{\\text{NGM}}}\\right)\n= \\alpha_j + \\mathbf{x}^{\\mathsf T}\\boldsymbol{\\beta}_j,\n$$\n\nwhere $\\mathbf{x}$ contains the exposure indicators and covariates included in a given candidate model. Each outcome contrast therefore has its own coefficient vector.\n\n### Analysis question: two binary models or one multinomial model?\n\nSeparate binary models and one multinomial model were compared as an implementation check. The candidate exposure and covariate specifications discussed during manuscript preparation are summarized below.\n\n|     Exposure     | Covariate set 1 | Covariate set 2 | Covariate set 3 |\n|:----------------:|:---------------:|:---------------:|:---------------:|\n|       PRS        |      prs1       |      prs2       |      prs3       |\n|      Coffee      |      cof1       |      cof2       |      cof3       |\n|   PRS + Coffee   |    prs_cof1     |    prs_cof2     |    prs_cof3     |\n| PRS + Coffee + PRS $\\times$ Coffee | prs_cof_i1 | prs_cof_i2 | prs_cof_i3 |\n\n: Candidate models {#tbl-models}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## PRS-only candidate models\nprs1 <- formula(Diabetes ~ PRS + Age + Sex)\nprs2 <- update(prs1, . ~ . + BMI + Alcohol + Smoking + Step_wake + DHD + KCal)\nprs3 <- update(prs2, . ~ . + CVD + Chol + OMAP + Med_HT + Med_LP + Sugar + B1_VD1 + Education)\n\n## Coffee-only candidate models\ncof1 <- update(prs1, . ~ Coffee - PRS + .)\ncof2 <- update(prs2, . ~ Coffee - PRS + .) \ncof3 <- update(prs3, . ~ Coffee - PRS + .)\n\n## Joint main-effects and interaction candidate models\nprs_cof1 <- update(prs1, . ~ Coffee + .)\nprs_cof2 <- update(prs2, . ~ Coffee + .)    \nprs_cof3 <- update(prs3, . ~ Coffee + .)\n\nprs_cof_i1 <- update(prs_cof1, . ~ PRS:Coffee + .)\nprs_cof_i2 <- update(prs_cof2, . ~ PRS:Coffee + .)\nprs_cof_i3 <- update(prs_cof3, . ~ PRS:Coffee + .)\n```\n:::\n\n\n## PRS association: comparison of implementations\n\n### Two binary logistic regressions\n\n#### NGM vs. Prediabetes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprediabetes <- diabetes |> filter(Diabetes %in% c(\"NGM\", \"Pre\"))\ndim(prediabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4889   20\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(prediabetes$Diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n NGM  Pre T2DM \n3944  945    0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprs3_bl_pre <- glm(prs3, family = binomial(link = \"logit\"), data = prediabetes)\nsummary(prs3_bl_pre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = prs3, family = binomial(link = \"logit\"), data = prediabetes)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -8.004e+00  7.002e-01 -11.432  < 2e-16 ***\nPRSMedium        3.017e-01  9.634e-02   3.131 0.001740 ** \nPRSHigh          4.352e-01  9.676e-02   4.498 6.85e-06 ***\nAge              4.734e-02  5.518e-03   8.579  < 2e-16 ***\nSexFemale       -2.683e-01  9.477e-02  -2.831 0.004642 ** \nBMI              1.116e-01  1.070e-02  10.425  < 2e-16 ***\nAlcohol          2.683e-03  3.236e-03   0.829 0.407153    \nSmokingFormer    9.964e-02  8.678e-02   1.148 0.250907    \nSmokingCurrent  -4.150e-02  1.396e-01  -0.297 0.766183    \nStep_wake       -1.806e-03  1.065e-03  -1.696 0.089835 .  \nDHD             -9.282e-03  2.966e-03  -3.129 0.001752 ** \nKCal            -1.092e-04  7.306e-05  -1.495 0.135044    \nCVDYes          -1.994e-01  1.157e-01  -1.722 0.085002 .  \nChol             9.577e-02  4.290e-02   2.232 0.025597 *  \nOMAP             1.457e-02  3.767e-03   3.869 0.000109 ***\nMed_HTYes        4.078e-01  9.238e-02   4.414 1.01e-05 ***\nMed_LPYes        6.212e-01  1.076e-01   5.774 7.75e-09 ***\nSugar           -3.767e-03  5.763e-03  -0.654 0.513348    \nB1_VD1No        -5.004e-01  9.011e-02  -5.553 2.80e-08 ***\nB1_VD1Unknow    -3.051e-01  1.245e-01  -2.450 0.014305 *  \nEducationMedium -2.258e-02  1.053e-01  -0.214 0.830219    \nEducationHigh   -6.935e-02  9.790e-02  -0.708 0.478690    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 4800.6  on 4888  degrees of freedom\nResidual deviance: 4151.3  on 4867  degrees of freedom\nAIC: 4195.3\n\nNumber of Fisher Scoring iterations: 5\n```\n\n\n:::\n\n```{.r .cell-code}\nlogistic.display(prs3_bl_pre)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLogistic regression predicting Diabetes \n \n                       crude OR(95%CI)         adj. OR(95%CI)         \nPRS: ref.=Low                                                         \n   Medium              1.36 (1.14,1.62)        1.35 (1.12,1.63)       \n   High                1.58 (1.33,1.89)        1.55 (1.28,1.87)       \n                                                                      \nAge (cont. var.)       1.06 (1.06,1.07)        1.05 (1.04,1.06)       \n                                                                      \nSex: Female vs Male    0.62 (0.54,0.72)        0.76 (0.64,0.92)       \n                                                                      \nBMI (cont. var.)       1.16 (1.14,1.18)        1.12 (1.09,1.14)       \n                                                                      \nAlcohol (cont. var.)   1.0125 (1.0073,1.0176)  1.0027 (0.9963,1.0091) \n                                                                      \nSmoking: ref.=Never                                                   \n   Former              1.52 (1.3,1.77)         1.1 (0.93,1.31)        \n   Current             1.17 (0.92,1.5)         0.96 (0.73,1.26)       \n                                                                      \nStep_wake (cont. var.) 0.9939 (0.992,0.9958)   0.9982 (0.9961,1.0003) \n                                                                      \nDHD (cont. var.)       0.9869 (0.9824,0.9915)  0.9908 (0.985,0.9965)  \n                                                                      \nKCal (cont. var.)      1 (0.9998,1.0001)       0.9999 (0.9997,1)      \n                                                                      \nCVD: Yes vs No         1.53 (1.27,1.86)        0.82 (0.65,1.03)       \n                                                                      \nChol (cont. var.)      0.93 (0.86,0.99)        1.1 (1.01,1.2)         \n                                                                      \nOMAP (cont. var.)      1.03 (1.03,1.04)        1.01 (1.01,1.02)       \n                                                                      \nMed_HT: Yes vs No      2.99 (2.58,3.47)        1.5 (1.25,1.8)         \n                                                                      \nMed_LP: Yes vs No      2.92 (2.49,3.43)        1.86 (1.51,2.3)        \n                                                                      \nSugar (cont. var.)     0.9994 (0.9893,1.0096)  0.9962 (0.985,1.0076)  \n                                                                      \nB1_VD1: ref.=Yes                                                      \n   No                  0.6 (0.51,0.7)          0.61 (0.51,0.72)       \n   Unknow              0.78 (0.62,0.97)        0.74 (0.58,0.94)       \n                                                                      \nEducation: ref.=Low                                                   \n   Medium              0.62 (0.51,0.74)        0.98 (0.8,1.2)         \n   High                0.58 (0.49,0.68)        0.93 (0.77,1.13)       \n                                                                      \n                       P(Wald's test) P(LR-test)\nPRS: ref.=Low                         < 0.001   \n   Medium              0.002                    \n   High                < 0.001                  \n                                                \nAge (cont. var.)       < 0.001        < 0.001   \n                                                \nSex: Female vs Male    0.005          0.005     \n                                                \nBMI (cont. var.)       < 0.001        < 0.001   \n                                                \nAlcohol (cont. var.)   0.407          0.409     \n                                                \nSmoking: ref.=Never                   0.377     \n   Former              0.251                    \n   Current             0.766                    \n                                                \nStep_wake (cont. var.) 0.09           0.089     \n                                                \nDHD (cont. var.)       0.002          0.002     \n                                                \nKCal (cont. var.)      0.135          0.134     \n                                                \nCVD: Yes vs No         0.085          0.082     \n                                                \nChol (cont. var.)      0.026          0.026     \n                                                \nOMAP (cont. var.)      < 0.001        < 0.001   \n                                                \nMed_HT: Yes vs No      < 0.001        < 0.001   \n                                                \nMed_LP: Yes vs No      < 0.001        < 0.001   \n                                                \nSugar (cont. var.)     0.513          0.51      \n                                                \nB1_VD1: ref.=Yes                      < 0.001   \n   No                  < 0.001                  \n   Unknow              0.014                    \n                                                \nEducation: ref.=Low                   0.768     \n   Medium              0.83                     \n   High                0.479                    \n                                                \nLog-likelihood = -2075.635\nNo. of observations = 4889\nAIC value = 4195.2701\n```\n\n\n:::\n:::\n\n\n#### NGM vs. T2DM\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2dm <- diabetes |> filter(Diabetes %in% c(\"NGM\", \"T2DM\"))\ndim(t2dm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5279   20\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(t2dm$Diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n NGM  Pre T2DM \n3944    0 1335 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprs3_bl_t2dm <- glm(prs3, family = binomial(link = \"logit\"), data = t2dm)\nsummary(prs3_bl_t2dm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = prs3, family = binomial(link = \"logit\"), data = t2dm)\n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -7.540e+00  8.516e-01  -8.854  < 2e-16 ***\nPRSMedium        8.101e-01  1.240e-01   6.531 6.53e-11 ***\nPRSHigh          1.198e+00  1.215e-01   9.860  < 2e-16 ***\nAge              5.366e-02  6.552e-03   8.189 2.63e-16 ***\nSexFemale       -8.024e-01  1.156e-01  -6.942 3.87e-12 ***\nBMI              1.741e-01  1.239e-02  14.055  < 2e-16 ***\nAlcohol         -7.559e-03  3.878e-03  -1.949 0.051299 .  \nSmokingFormer    1.074e-01  1.051e-01   1.022 0.306925    \nSmokingCurrent   3.982e-01  1.571e-01   2.534 0.011270 *  \nStep_wake       -6.260e-03  1.294e-03  -4.836 1.33e-06 ***\nDHD             -1.135e-02  3.545e-03  -3.202 0.001363 ** \nKCal            -7.423e-05  8.491e-05  -0.874 0.382003    \nCVDYes          -4.544e-01  1.250e-01  -3.636 0.000277 ***\nChol            -4.487e-01  5.425e-02  -8.270  < 2e-16 ***\nOMAP             2.329e-02  4.630e-03   5.030 4.90e-07 ***\nMed_HTYes        7.470e-01  1.046e-01   7.141 9.28e-13 ***\nMed_LPYes        1.473e+00  1.128e-01  13.058  < 2e-16 ***\nSugar           -4.791e-02  8.685e-03  -5.516 3.47e-08 ***\nB1_VD1No        -1.620e+00  1.055e-01 -15.353  < 2e-16 ***\nB1_VD1Unknow    -1.023e+00  1.399e-01  -7.317 2.54e-13 ***\nEducationMedium -1.917e-02  1.203e-01  -0.159 0.873423    \nEducationHigh   -2.835e-01  1.187e-01  -2.388 0.016922 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 5970.4  on 5278  degrees of freedom\nResidual deviance: 3007.7  on 5257  degrees of freedom\nAIC: 3051.7\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n\n```{.r .cell-code}\nlogistic.display(prs3_bl_t2dm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLogistic regression predicting Diabetes \n \n                       crude OR(95%CI)         adj. OR(95%CI)         \nPRS: ref.=Low                                                         \n   Medium              2.41 (2.02,2.86)        2.25 (1.76,2.87)       \n   High                3.49 (2.95,4.12)        3.31 (2.61,4.2)        \n                                                                      \nAge (cont. var.)       1.08 (1.07,1.09)        1.06 (1.04,1.07)       \n                                                                      \nSex: Female vs Male    0.34 (0.3,0.38)         0.45 (0.36,0.56)       \n                                                                      \nBMI (cont. var.)       1.28 (1.26,1.31)        1.19 (1.16,1.22)       \n                                                                      \nAlcohol (cont. var.)   0.9985 (0.9936,1.0033)  0.9925 (0.985,1)       \n                                                                      \nSmoking: ref.=Never                                                   \n   Former              1.72 (1.49,1.97)        1.11 (0.91,1.37)       \n   Current             1.68 (1.37,2.05)        1.49 (1.09,2.03)       \n                                                                      \nStep_wake (cont. var.) 0.9836 (0.9818,0.9854)  0.9938 (0.9912,0.9963) \n                                                                      \nDHD (cont. var.)       0.98 (0.97,0.98)        0.99 (0.98,1)          \n                                                                      \nKCal (cont. var.)      0.9999 (0.9998,1)       0.9999 (0.9998,1.0001) \n                                                                      \nCVD: Yes vs No         2.71 (2.33,3.16)        0.63 (0.5,0.81)        \n                                                                      \nChol (cont. var.)      0.35 (0.33,0.38)        0.64 (0.57,0.71)       \n                                                                      \nOMAP (cont. var.)      1.05 (1.04,1.05)        1.02 (1.01,1.03)       \n                                                                      \nMed_HT: Yes vs No      8.82 (7.67,10.15)       2.11 (1.72,2.59)       \n                                                                      \nMed_LP: Yes vs No      14.31 (12.35,16.59)     4.36 (3.5,5.44)        \n                                                                      \nSugar (cont. var.)     0.97 (0.95,0.98)        0.95 (0.94,0.97)       \n                                                                      \nB1_VD1: ref.=Yes                                                      \n   No                  0.19 (0.16,0.22)        0.2 (0.16,0.24)        \n   Unknow              0.41 (0.34,0.5)         0.36 (0.27,0.47)       \n                                                                      \nEducation: ref.=Low                                                   \n   Medium              0.57 (0.49,0.67)        0.98 (0.77,1.24)       \n   High                0.36 (0.31,0.42)        0.75 (0.6,0.95)        \n                                                                      \n                       P(Wald's test) P(LR-test)\nPRS: ref.=Low                         < 0.001   \n   Medium              < 0.001                  \n   High                < 0.001                  \n                                                \nAge (cont. var.)       < 0.001        < 0.001   \n                                                \nSex: Female vs Male    < 0.001        < 0.001   \n                                                \nBMI (cont. var.)       < 0.001        < 0.001   \n                                                \nAlcohol (cont. var.)   0.051          0.05      \n                                                \nSmoking: ref.=Never                   0.041     \n   Former              0.307                    \n   Current             0.011                    \n                                                \nStep_wake (cont. var.) < 0.001        < 0.001   \n                                                \nDHD (cont. var.)       0.001          0.001     \n                                                \nKCal (cont. var.)      0.382          0.382     \n                                                \nCVD: Yes vs No         < 0.001        < 0.001   \n                                                \nChol (cont. var.)      < 0.001        < 0.001   \n                                                \nOMAP (cont. var.)      < 0.001        < 0.001   \n                                                \nMed_HT: Yes vs No      < 0.001        < 0.001   \n                                                \nMed_LP: Yes vs No      < 0.001        < 0.001   \n                                                \nSugar (cont. var.)     < 0.001        < 0.001   \n                                                \nB1_VD1: ref.=Yes                      < 0.001   \n   No                  < 0.001                  \n   Unknow              < 0.001                  \n                                                \nEducation: ref.=Low                   0.03      \n   Medium              0.873                    \n   High                0.017                    \n                                                \nLog-likelihood = -1503.8424\nNo. of observations = 5279\nAIC value = 3051.6849\n```\n\n\n:::\n:::\n\n\n### Multinomial logistic regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprs3_ml <- multinom(prs3, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  69 (44 variable)\ninitial  value 6837.762885 \niter  10 value 5215.529946\niter  20 value 4639.168406\niter  30 value 4273.319863\niter  40 value 4017.408486\niter  50 value 3983.845642\nfinal  value 3983.621664 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(prs3_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmultinom(formula = prs3, data = diabetes)\n\nCoefficients:\n     (Intercept) PRSMedium   PRSHigh        Age SexFemale       BMI\nPre    -7.993443 0.3048323 0.4590396 0.04691694 -0.269743 0.1105872\nT2DM   -7.530014 0.8205179 1.1457251 0.04937704 -0.845876 0.1727318\n          Alcohol SmokingFormer SmokingCurrent    Step_wake          DHD\nPre   0.003132189     0.1205212     0.03541554 -0.001591920 -0.008673513\nT2DM -0.008483711     0.1014127     0.28413325 -0.007081803 -0.008881605\n              KCal     CVDYes        Chol       OMAP Med_HTYes Med_LPYes\nPre  -1.252987e-04 -0.2092194  0.09181539 0.01470355 0.4051368  0.647377\nT2DM -8.870268e-05 -0.5104388 -0.41867134 0.02422280 0.7199281  1.508455\n            Sugar   B1_VD1No B1_VD1Unknow EducationMedium EducationHigh\nPre  -0.004413489 -0.4966035   -0.3253156     -0.06624586     -0.107326\nT2DM -0.044371036 -1.6066637   -0.9962776      0.04357004     -0.277215\n\nStd. Errors:\n     (Intercept)  PRSMedium    PRSHigh         Age  SexFemale         BMI\nPre  0.005541274 0.08199097 0.08180552 0.004718533 0.08838194 0.009288211\nT2DM 0.004586410 0.06104669 0.06058859 0.005198003 0.09790667 0.010027835\n         Alcohol SmokingFormer SmokingCurrent   Step_wake         DHD\nPre  0.003071018    0.07749479     0.09140973 0.001011571 0.002726991\nT2DM 0.003585977    0.08396675     0.07539267 0.001174780 0.003033971\n             KCal     CVDYes       Chol        OMAP  Med_HTYes  Med_LPYes\nPre  6.883390e-05 0.07184194 0.03926264 0.003353974 0.07653429 0.07178370\nT2DM 7.598204e-05 0.06452109 0.04711608 0.003757188 0.07818381 0.06507821\n           Sugar  B1_VD1No B1_VD1Unknow EducationMedium EducationHigh\nPre  0.005542964 0.0740401   0.08135444      0.07884324    0.07481118\nT2DM 0.008251040 0.0811196   0.07534407      0.07216372    0.07256924\n\nResidual Deviance: 7967.243 \nAIC: 8055.243 \n```\n\n\n:::\n\n```{.r .cell-code}\nmlogit.display(prs3_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOutcome =Diabetes; Referent group = NGM \n                Pre                            T2DM                          \n                Coeff./SE      RRR(95%CI)      Coeff./SE      RRR(95%CI)     \n(Intercept)     -7.99/0.006NA  -               -7.53/0.005NA  -              \nPRSMedium       0.3/0.082***   1.36(1.16,1.59) 0.82/0.061***  2.27(2.02,2.56)\nPRSHigh         0.46/0.082***  1.58(1.35,1.86) 1.15/0.061***  3.14(2.79,3.54)\nAge             0.05/0.005***  1.05(1.04,1.06) 0.05/0.005***  1.05(1.04,1.06)\nSexFemale       -0.27/0.088**  0.76(0.64,0.91) -0.85/0.098*** 0.43(0.35,0.52)\nBMI             0.11/0.009***  1.12(1.1,1.14)  0.17/0.01***   1.19(1.17,1.21)\nAlcohol         0/0.003        1(1,1.01)       -0.01/0.004*   0.99(0.98,1)   \nSmokingFormer   0.12/0.077     1.13(0.97,1.31) 0.1/0.084      1.11(0.94,1.3) \nSmokingCurrent  0.04/0.091     1.04(0.87,1.24) 0.28/0.075***  1.33(1.15,1.54)\nStep_wake       0/0.001        1(1,1)          -0.01/0.001*** 0.99(0.99,1)   \nDHD             -0.01/0.003**  0.99(0.99,1)    -0.01/0.003**  0.99(0.99,1)   \nKCal            0/0            1(1,1)          0/0            1(1,1)         \nCVDYes          -0.21/0.072**  0.81(0.7,0.93)  -0.51/0.065*** 0.6(0.53,0.68) \nChol            0.09/0.039*    1.1(1.01,1.18)  -0.42/0.047*** 0.66(0.6,0.72) \nOMAP            0.01/0.003***  1.01(1.01,1.02) 0.02/0.004***  1.02(1.02,1.03)\nMed_HTYes       0.41/0.077***  1.5(1.29,1.74)  0.72/0.078***  2.05(1.76,2.39)\nMed_LPYes       0.65/0.072***  1.91(1.66,2.2)  1.51/0.065***  4.52(3.98,5.13)\nSugar           0/0.006        1(0.98,1.01)    -0.04/0.008*** 0.96(0.94,0.97)\nB1_VD1No        -0.5/0.074***  0.61(0.53,0.7)  -1.61/0.081*** 0.2(0.17,0.24) \nB1_VD1Unknow    -0.33/0.081*** 0.72(0.62,0.85) -1/0.075***    0.37(0.32,0.43)\nEducationMedium -0.07/0.079    0.94(0.8,1.09)  0.04/0.072     1.04(0.91,1.2) \nEducationHigh   -0.11/0.075    0.9(0.78,1.04)  -0.28/0.073*** 0.76(0.66,0.87)\n\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1  \n\nResidual Deviance: 7967.24 \nAIC = 8055.24 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Intermediate comparison\n\nIn this dataset, the estimated PRS associations from the multinomial model were similar to those obtained from the two separate binary models. This was a descriptive implementation check and does not establish that the approaches are generally equivalent. The binary models use different outcome-specific subsets, whereas the multinomial model represents all three outcome categories within one model. The subsequent working tables therefore use the multinomial implementation.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprs1_ml <- multinom(prs1, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  18 (10 variable)\ninitial  value 6837.762885 \niter  10 value 5404.157593\nfinal  value 5164.014496 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nprs2_ml <- multinom(prs2, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  39 (24 variable)\ninitial  value 6837.762885 \niter  10 value 5290.331013\niter  20 value 4842.276842\niter  30 value 4605.592708\nfinal  value 4605.590003 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nlrtest(prs1_ml, prs2_ml, prs3_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: Diabetes ~ PRS + Age + Sex\nModel 2: Diabetes ~ PRS + Age + Sex + BMI + Alcohol + Smoking + Step_wake + \n    DHD + KCal\nModel 3: Diabetes ~ PRS + Age + Sex + BMI + Alcohol + Smoking + Step_wake + \n    DHD + KCal + CVD + Chol + OMAP + Med_HT + Med_LP + Sugar + \n    B1_VD1 + Education\n  #Df  LogLik Df  Chisq Pr(>Chisq)    \n1  10 -5164.0                         \n2  24 -4605.6 14 1116.8  < 2.2e-16 ***\n3  44 -3983.6 20 1243.9  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nget_OR_CI <- function(multi_model, DV_level, EV_level, alpha = 0.05) {\n  esti <- coef(multi_model)[DV_level, , drop = FALSE]\n  .cov_mat <- vcov(multi_model)\n  .select_variable <- str_detect(colnames(.cov_mat), DV_level)\n  cov_mat <- .cov_mat[.select_variable, .select_variable]\n  \n  cont <- matrix(multi_model$coefnames %in% EV_level, nrow = 1)\n  l <- cont %*% t(esti)\n  OR <- exp(l) |> round(2)\n  SE <- sqrt(cont %*% cov_mat %*% t(cont))\n  lower_CI <- exp(l - qnorm(1-alpha/2) * SE) |> round(2)\n  upper_CI <- exp(l + qnorm(1-alpha/2) * SE) |> round(2)\n  \n  str_glue(\"{OR} <br> ({lower_CI}, {upper_CI})\")\n}\n```\n:::\n\n\n\n::: {#tbl-prs-effect .cell tbl-cap='Association between PRS and prediabetes/T2DM'}\n\n```{.r .cell-code}\nlevels <- c(\"Low\", \"Medium\", \"High\") \nPRSlevels <- str_glue(\"PRS{levels}\")\n\nprs_OR_table <- tibble(\n  level = levels ,\n  Pre_prs1 = map_chr(PRSlevels, ~ get_OR_CI(prs1_ml, \"Pre\", .)),\n  Pre_prs2 = map_chr(PRSlevels, ~ get_OR_CI(prs2_ml, \"Pre\", .)),\n  Pre_prs3 = map_chr(PRSlevels, ~ get_OR_CI(prs3_ml, \"Pre\", .)),\n  T2DM_prs1 = map_chr(PRSlevels, ~ get_OR_CI(prs1_ml, \"T2DM\", .)),\n  T2DM_prs2 = map_chr(PRSlevels, ~ get_OR_CI(prs2_ml, \"T2DM\", .)),\n  T2DM_prs3 = map_chr(PRSlevels, ~ get_OR_CI(prs3_ml, \"T2DM\", .)))\n\ngt(prs_OR_table, rowname_col = \"level\") |>\n  tab_stubhead(label = \"PRS\") |>\n  tab_spanner(label = \"Pre\", columns = starts_with(\"Pre\")) |>\n  tab_spanner(label = \"T2DM\", columns = starts_with(\"T2DM\")) |>\n  cols_label(ends_with(\"1\") ~ \"M1\",\n             ends_with(\"2\") ~ \"M2\",\n             ends_with(\"3\") ~ \"M3\") |>\n  fmt_markdown()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wxumtucdbn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wxumtucdbn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wxumtucdbn thead, #wxumtucdbn tbody, #wxumtucdbn tfoot, #wxumtucdbn tr, #wxumtucdbn td, #wxumtucdbn th {\n  border-style: none;\n}\n\n#wxumtucdbn p {\n  margin: 0;\n  padding: 0;\n}\n\n#wxumtucdbn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wxumtucdbn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wxumtucdbn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wxumtucdbn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wxumtucdbn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wxumtucdbn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wxumtucdbn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wxumtucdbn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wxumtucdbn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wxumtucdbn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wxumtucdbn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wxumtucdbn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wxumtucdbn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wxumtucdbn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wxumtucdbn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxumtucdbn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wxumtucdbn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wxumtucdbn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wxumtucdbn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxumtucdbn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wxumtucdbn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxumtucdbn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wxumtucdbn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxumtucdbn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wxumtucdbn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wxumtucdbn .gt_left {\n  text-align: left;\n}\n\n#wxumtucdbn .gt_center {\n  text-align: center;\n}\n\n#wxumtucdbn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wxumtucdbn .gt_font_normal {\n  font-weight: normal;\n}\n\n#wxumtucdbn .gt_font_bold {\n  font-weight: bold;\n}\n\n#wxumtucdbn .gt_font_italic {\n  font-style: italic;\n}\n\n#wxumtucdbn .gt_super {\n  font-size: 65%;\n}\n\n#wxumtucdbn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wxumtucdbn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wxumtucdbn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wxumtucdbn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wxumtucdbn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wxumtucdbn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wxumtucdbn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wxumtucdbn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wxumtucdbn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\">PRS</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"Pre\">\n        <div class=\"gt_column_spanner\">Pre</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"T2DM\">\n        <div class=\"gt_column_spanner\">T2DM</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_prs1\">M1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_prs2\">M2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_prs3\">M3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_prs1\">M1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_prs2\">M2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_prs3\">M3</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TG93\"><span class='gt_from_md'>Low</span></span></th>\n<td headers=\"stub_1_1 Pre_prs1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 Pre_prs2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 Pre_prs3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 T2DM_prs1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 T2DM_prs2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 T2DM_prs3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TWVkaXVt\"><span class='gt_from_md'>Medium</span></span></th>\n<td headers=\"stub_1_2 Pre_prs1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4zOCA8YnI+ICgxLjE1LCAxLjY1KQ==\"><span class='gt_from_md'>1.38 <br> (1.15, 1.65)</span></span></td>\n<td headers=\"stub_1_2 Pre_prs2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS40IDxicj4gKDEuMjEsIDEuNjIp\"><span class='gt_from_md'>1.4 <br> (1.21, 1.62)</span></span></td>\n<td headers=\"stub_1_2 Pre_prs3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4zNiA8YnI+ICgxLjE2LCAxLjU5KQ==\"><span class='gt_from_md'>1.36 <br> (1.16, 1.59)</span></span></td>\n<td headers=\"stub_1_2 T2DM_prs1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi40NSA8YnI+ICgyLjA1LCAyLjk0KQ==\"><span class='gt_from_md'>2.45 <br> (2.05, 2.94)</span></span></td>\n<td headers=\"stub_1_2 T2DM_prs2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi41NCA8YnI+ICgyLjI2LCAyLjg2KQ==\"><span class='gt_from_md'>2.54 <br> (2.26, 2.86)</span></span></td>\n<td headers=\"stub_1_2 T2DM_prs3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi4yNyA8YnI+ICgyLjAyLCAyLjU2KQ==\"><span class='gt_from_md'>2.27 <br> (2.02, 2.56)</span></span></td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"SGlnaA==\"><span class='gt_from_md'>High</span></span></th>\n<td headers=\"stub_1_3 Pre_prs1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS42NiA8YnI+ICgxLjM5LCAxLjk5KQ==\"><span class='gt_from_md'>1.66 <br> (1.39, 1.99)</span></span></td>\n<td headers=\"stub_1_3 Pre_prs2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS43NCA8YnI+ICgxLjUsIDIuMDEp\"><span class='gt_from_md'>1.74 <br> (1.5, 2.01)</span></span></td>\n<td headers=\"stub_1_3 Pre_prs3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS41OCA8YnI+ICgxLjM1LCAxLjg2KQ==\"><span class='gt_from_md'>1.58 <br> (1.35, 1.86)</span></span></td>\n<td headers=\"stub_1_3 T2DM_prs1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My43NiA8YnI+ICgzLjE2LCA0LjQ5KQ==\"><span class='gt_from_md'>3.76 <br> (3.16, 4.49)</span></span></td>\n<td headers=\"stub_1_3 T2DM_prs2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"NC4xOCA8YnI+ICgzLjcyLCA0Ljcp\"><span class='gt_from_md'>4.18 <br> (3.72, 4.7)</span></span></td>\n<td headers=\"stub_1_3 T2DM_prs3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My4xNCA8YnI+ICgyLjc5LCAzLjU0KQ==\"><span class='gt_from_md'>3.14 <br> (2.79, 3.54)</span></span></td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Coffee association: working table reproduction\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncof1_ml <- multinom(cof1, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  24 (14 variable)\ninitial  value 6837.762885 \niter  10 value 5398.637887\niter  20 value 5159.349831\nfinal  value 5159.349135 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\ncof2_ml <- multinom(cof2, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  45 (28 variable)\ninitial  value 6837.762885 \niter  10 value 5290.261102\niter  20 value 4845.902793\niter  30 value 4641.391553\nfinal  value 4601.460847 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\ncof3_ml <- multinom(cof3, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  75 (48 variable)\ninitial  value 6837.762885 \niter  10 value 5215.456459\niter  20 value 4635.906609\niter  30 value 4251.564367\niter  40 value 4014.806998\niter  50 value 3985.463039\nfinal  value 3978.814138 \nconverged\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-cof-effect .cell tbl-cap='Association between coffee consumption and prediabetes/T2DM'}\n\n```{.r .cell-code}\nCoflevels <- str_glue(\"Coffee{levels}\")\n\ncof_OR_table <- tibble(\n  level = levels ,\n  Pre_cof1 = map_chr(Coflevels, ~ get_OR_CI(cof1_ml, \"Pre\", .)),\n  Pre_cof2 = map_chr(Coflevels, ~ get_OR_CI(cof2_ml, \"Pre\", .)),\n  Pre_cof3 = map_chr(Coflevels, ~ get_OR_CI(cof3_ml, \"Pre\", .)),\n  T2DM_cof1 = map_chr(Coflevels, ~ get_OR_CI(cof1_ml, \"T2DM\", .)),\n  T2DM_cof2 = map_chr(Coflevels, ~ get_OR_CI(cof2_ml, \"T2DM\", .)),\n  T2DM_cof3 = map_chr(Coflevels, ~ get_OR_CI(cof3_ml, \"T2DM\", .)))\n\ngt(cof_OR_table, rowname_col = \"level\") |>\n  tab_stubhead(label = \"Coffee\") |>\n  tab_spanner(label = \"Pre\", columns = starts_with(\"Pre\")) |>\n  tab_spanner(label = \"T2DM\", columns = starts_with(\"T2DM\")) |>\n  cols_label(ends_with(\"1\") ~ \"M1\",\n             ends_with(\"2\") ~ \"M2\",\n             ends_with(\"3\") ~ \"M3\") |>\n  fmt_markdown()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cqoanankmo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cqoanankmo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cqoanankmo thead, #cqoanankmo tbody, #cqoanankmo tfoot, #cqoanankmo tr, #cqoanankmo td, #cqoanankmo th {\n  border-style: none;\n}\n\n#cqoanankmo p {\n  margin: 0;\n  padding: 0;\n}\n\n#cqoanankmo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cqoanankmo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cqoanankmo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cqoanankmo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cqoanankmo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cqoanankmo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cqoanankmo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cqoanankmo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cqoanankmo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cqoanankmo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cqoanankmo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cqoanankmo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cqoanankmo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cqoanankmo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cqoanankmo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqoanankmo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cqoanankmo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cqoanankmo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cqoanankmo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqoanankmo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cqoanankmo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqoanankmo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cqoanankmo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqoanankmo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cqoanankmo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cqoanankmo .gt_left {\n  text-align: left;\n}\n\n#cqoanankmo .gt_center {\n  text-align: center;\n}\n\n#cqoanankmo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cqoanankmo .gt_font_normal {\n  font-weight: normal;\n}\n\n#cqoanankmo .gt_font_bold {\n  font-weight: bold;\n}\n\n#cqoanankmo .gt_font_italic {\n  font-style: italic;\n}\n\n#cqoanankmo .gt_super {\n  font-size: 65%;\n}\n\n#cqoanankmo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cqoanankmo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cqoanankmo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cqoanankmo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cqoanankmo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cqoanankmo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cqoanankmo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cqoanankmo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cqoanankmo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"a::stub\">Coffee</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"Pre\">\n        <div class=\"gt_column_spanner\">Pre</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"T2DM\">\n        <div class=\"gt_column_spanner\">T2DM</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_cof1\">M1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_cof2\">M2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_cof3\">M3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_cof1\">M1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_cof2\">M2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_cof3\">M3</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><th id=\"stub_1_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TG93\"><span class='gt_from_md'>Low</span></span></th>\n<td headers=\"stub_1_1 Pre_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 Pre_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 Pre_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 T2DM_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 T2DM_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"stub_1_1 T2DM_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td></tr>\n    <tr><th id=\"stub_1_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TWVkaXVt\"><span class='gt_from_md'>Medium</span></span></th>\n<td headers=\"stub_1_2 Pre_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MSA8YnI+ICgwLjY4LCAwLjk3KQ==\"><span class='gt_from_md'>0.81 <br> (0.68, 0.97)</span></span></td>\n<td headers=\"stub_1_2 Pre_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNywgMC45Mik=\"><span class='gt_from_md'>0.8 <br> (0.7, 0.92)</span></span></td>\n<td headers=\"stub_1_2 Pre_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNjksIDAuOTIp\"><span class='gt_from_md'>0.8 <br> (0.69, 0.92)</span></span></td>\n<td headers=\"stub_1_2 T2DM_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MiA8YnI+ICgwLjcsIDAuOTcp\"><span class='gt_from_md'>0.82 <br> (0.7, 0.97)</span></span></td>\n<td headers=\"stub_1_2 T2DM_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MyA8YnI+ICgwLjczLCAwLjk0KQ==\"><span class='gt_from_md'>0.83 <br> (0.73, 0.94)</span></span></td>\n<td headers=\"stub_1_2 T2DM_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNywgMC45MSk=\"><span class='gt_from_md'>0.8 <br> (0.7, 0.91)</span></span></td></tr>\n    <tr><th id=\"stub_1_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"SGlnaA==\"><span class='gt_from_md'>High</span></span></th>\n<td headers=\"stub_1_3 Pre_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC45IDxicj4gKDAuNzUsIDEuMDgp\"><span class='gt_from_md'>0.9 <br> (0.75, 1.08)</span></span></td>\n<td headers=\"stub_1_3 Pre_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44NSA8YnI+ICgwLjc0LCAwLjk3KQ==\"><span class='gt_from_md'>0.85 <br> (0.74, 0.97)</span></span></td>\n<td headers=\"stub_1_3 Pre_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MyA8YnI+ICgwLjcyLCAwLjk2KQ==\"><span class='gt_from_md'>0.83 <br> (0.72, 0.96)</span></span></td>\n<td headers=\"stub_1_3 T2DM_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC45NyA8YnI+ICgwLjgyLCAxLjE0KQ==\"><span class='gt_from_md'>0.97 <br> (0.82, 1.14)</span></span></td>\n<td headers=\"stub_1_3 T2DM_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44NyA8YnI+ICgwLjc2LCAwLjk5KQ==\"><span class='gt_from_md'>0.87 <br> (0.76, 0.99)</span></span></td>\n<td headers=\"stub_1_3 T2DM_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNywgMC45MSk=\"><span class='gt_from_md'>0.8 <br> (0.7, 0.91)</span></span></td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Coffee-by-PRS interaction: working table reproduction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprs_cof1_ml <- multinom(prs_cof1, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  24 (14 variable)\ninitial  value 6837.762885 \niter  10 value 5398.637887\niter  20 value 5159.349831\nfinal  value 5159.349135 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nprs_cof_i1_ml <- multinom(prs_cof_i1, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  36 (22 variable)\ninitial  value 6837.762885 \niter  10 value 5465.181242\niter  20 value 5199.344506\niter  30 value 5154.011791\niter  30 value 5154.011788\niter  30 value 5154.011788\nfinal  value 5154.011788 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nprs_cof1_ml\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCall:\nmultinom(formula = prs_cof1, data = diabetes)\n\nCoefficients:\n     (Intercept) CoffeeMedium  CoffeeHigh PRSMedium   PRSHigh        Age\nPre    -5.127968   -0.2087765 -0.10369891 0.3228881 0.5081659 0.06163677\nT2DM   -5.901011   -0.1941127 -0.03432375 0.8988806 1.3236497 0.07414162\n      SexFemale\nPre  -0.3943786\nT2DM -1.0023219\n\nResidual Deviance: 10318.7 \nAIC: 10346.7 \n```\n\n\n:::\n\n```{.r .cell-code}\nmlogit.display(prs_cof1_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOutcome =Diabetes; Referent group = NGM \n             Pre                            T2DM                         \n             Coeff./SE      RRR(95%CI)      Coeff./SE     RRR(95%CI)     \n(Intercept)  -5.13/0.305*** -               -5.9/0.29***  -              \nCoffeeMedium -0.21/0.089*   0.81(0.68,0.97) -0.19/0.083*  0.82(0.7,0.97) \nCoffeeHigh   -0.1/0.091     0.9(0.75,1.08)  -0.03/0.083   0.97(0.82,1.14)\nPRSMedium    0.32/0.092***  1.38(1.15,1.65) 0.9/0.092***  2.46(2.05,2.94)\nPRSHigh      0.51/0.091***  1.66(1.39,1.99) 1.32/0.09***  3.76(3.15,4.48)\nAge          0.06/0.005***  1.06(1.05,1.07) 0.07/0.004*** 1.08(1.07,1.09)\nSexFemale    -0.39/0.075*** 0.67(0.58,0.78) -1/0.071***   0.37(0.32,0.42)\n\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1  \n\nResidual Deviance: 10318.7 \nAIC = 10346.7 \n```\n\n\n:::\n\n```{.r .cell-code}\nmlogit.display(prs_cof_i1_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOutcome =Diabetes; Referent group = NGM \n                       Pre                            T2DM          \n                       Coeff./SE      RRR(95%CI)      Coeff./SE     \n(Intercept)            -5.13/0.311*** -               -5.75/0.297***\nCoffeeMedium           -0.31/0.159*   0.73(0.53,1)    -0.5/0.174**  \nCoffeeHigh             -0.01/0.158    0.99(0.72,1.34) -0.26/0.174   \nPRSMedium              0.28/0.148     1.32(0.99,1.76) 0.76/0.146*** \nPRSHigh                0.52/0.144***  1.68(1.27,2.23) 1.06/0.142*** \nAge                    0.06/0.005***  1.06(1.05,1.07) 0.07/0.004*** \nSexFemale              -0.39/0.075*** 0.67(0.58,0.78) -1/0.071***   \nCoffeeMedium:PRSMedium 0.14/0.221     1.16(0.75,1.78) 0.24/0.222    \nCoffeeHigh:PRSMedium   0/0.222        1(0.65,1.54)    0.23/0.222    \nCoffeeMedium:PRSHigh   0.19/0.219     1.21(0.79,1.86) 0.54/0.217*   \nCoffeeHigh:PRSHigh     -0.24/0.221    0.79(0.51,1.21) 0.33/0.215    \n                                      \n                       RRR(95%CI)     \n(Intercept)            -              \nCoffeeMedium           0.61(0.43,0.85)\nCoffeeHigh             0.77(0.55,1.08)\nPRSMedium              2.13(1.6,2.84) \nPRSHigh                2.88(2.18,3.8) \nAge                    1.08(1.07,1.09)\nSexFemale              0.37(0.32,0.42)\nCoffeeMedium:PRSMedium 1.27(0.82,1.97)\nCoffeeHigh:PRSMedium   1.26(0.81,1.94)\nCoffeeMedium:PRSHigh   1.71(1.12,2.61)\nCoffeeHigh:PRSHigh     1.4(0.92,2.13) \n\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1  \n\nResidual Deviance: 10308.02 \nAIC = 10352.02 \n```\n\n\n:::\n\n```{.r .cell-code}\nlrtest(prs_cof1_ml, prs_cof_i1_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: Diabetes ~ Coffee + PRS + Age + Sex\nModel 2: Diabetes ~ Coffee + PRS + Age + Sex + PRS:Coffee\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1  14 -5159.3                     \n2  22 -5154.0  8 10.675     0.2208\n```\n\n\n:::\n\n```{.r .cell-code}\nprs_cof2_ml <- multinom(prs_cof2, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  45 (28 variable)\ninitial  value 6837.762885 \niter  10 value 5290.261102\niter  20 value 4845.902793\niter  30 value 4641.391553\nfinal  value 4601.460847 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nprs_cof_i2_ml <- multinom(prs_cof_i2, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  57 (36 variable)\ninitial  value 6837.762885 \niter  10 value 5289.996854\niter  20 value 4847.821699\niter  30 value 4690.907647\niter  40 value 4596.380913\nfinal  value 4595.158389 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nlrtest(prs_cof2_ml, prs_cof_i2_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: Diabetes ~ Coffee + PRS + Age + Sex + BMI + Alcohol + Smoking + \n    Step_wake + DHD + KCal\nModel 2: Diabetes ~ Coffee + PRS + Age + Sex + BMI + Alcohol + Smoking + \n    Step_wake + DHD + KCal + PRS:Coffee\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1  28 -4601.5                     \n2  36 -4595.2  8 12.605     0.1262\n```\n\n\n:::\n\n```{.r .cell-code}\nprs_cof3_ml <- multinom(prs_cof3, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  75 (48 variable)\ninitial  value 6837.762885 \niter  10 value 5215.456459\niter  20 value 4635.906609\niter  30 value 4251.564367\niter  40 value 4014.806998\niter  50 value 3985.463039\nfinal  value 3978.814138 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nprs_cof_i3_ml <- multinom(prs_cof_i3, data = diabetes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# weights:  87 (56 variable)\ninitial  value 6837.762885 \niter  10 value 5215.195654\niter  20 value 4636.177404\niter  30 value 4155.562209\niter  40 value 4066.224939\niter  50 value 3998.661572\niter  60 value 3975.634350\nfinal  value 3973.411479 \nconverged\n```\n\n\n:::\n\n```{.r .cell-code}\nlrtest(prs_cof3_ml, prs_cof_i3_ml)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLikelihood ratio test\n\nModel 1: Diabetes ~ Coffee + PRS + Age + Sex + BMI + Alcohol + Smoking + \n    Step_wake + DHD + KCal + CVD + Chol + OMAP + Med_HT + Med_LP + \n    Sugar + B1_VD1 + Education\nModel 2: Diabetes ~ Coffee + PRS + Age + Sex + BMI + Alcohol + Smoking + \n    Step_wake + DHD + KCal + CVD + Chol + OMAP + Med_HT + Med_LP + \n    Sugar + B1_VD1 + Education + PRS:Coffee\n  #Df  LogLik Df  Chisq Pr(>Chisq)\n1  48 -3978.8                     \n2  56 -3973.4  8 10.805      0.213\n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Working decision on interaction terms\n\nFor the candidate models shown above, the likelihood-ratio tests did not provide evidence that adding the categorical coffee-by-PRS interaction terms improved model fit. The corresponding main-effects models (`prs_cof1`, `prs_cof2`, and `prs_cof3`) were therefore retained for the working association tables. This decision should not be interpreted as proof that interaction is absent; the published article reports the final interaction analysis and its interpretation.\n:::\n\nThe next section reconstructs a working joint-category table considered during manuscript preparation. Model `prs_cof1` includes categorical indicators for coffee consumption and PRS, with low coffee consumption and low PRS as the reference combination. For prediabetes versus NGM, its linear predictor is\n\n$$\n\\ln\\left(\\frac{p_{\\text{Pre}}}{p_{\\text{NGM}}} \\right) = \\alpha_{11} + \\beta_{11} \\text{CoffeeMedium} + \\beta_{12} \\text{CoffeeHigh} + \\beta_{13} \\text{PRSMedium} + \\beta_{14} \\text{PRSHigh} + \\gamma_{11} \\text{Age} + \\gamma_{12} \\text{SexFemale}\n$$\n\nFor either outcome contrast $j$, let $\\mathbf{c}_{c,p}$ select the coefficients needed to compare coffee category $c$ and PRS category $p$ with the low-coffee, low-PRS reference combination while holding covariates fixed. The estimated log odds ratio is\n\n$$\n\\widehat{\\ell}_{j,c,p}\n= \\mathbf{c}_{c,p}^{\\mathsf T}\\widehat{\\boldsymbol{\\beta}}_j,\n$$\n\nand the corresponding odds ratio is\n\n$$\n\\widehat{\\operatorname{OR}}_{j,c,p}\n= \\exp\\left(\\widehat{\\ell}_{j,c,p}\\right).\n$$\n\nIts estimated variance and 95% Wald confidence interval are\n\n$$\n\\widehat{\\operatorname{Var}}\\left(\\widehat{\\ell}_{j,c,p}\\right)\n= \\mathbf{c}_{c,p}^{\\mathsf T}\n  \\widehat{\\operatorname{Var}}\\left(\\widehat{\\boldsymbol{\\beta}}_j\\right)\n  \\mathbf{c}_{c,p},\n$$\n\n$$\n95\\%\\ \\operatorname{CI}\n= \\exp\\left[\n  \\widehat{\\ell}_{j,c,p}\n  \\mathbin{\\pm} z_{.975}\n  \\sqrt{\\widehat{\\operatorname{Var}}\\left(\\widehat{\\ell}_{j,c,p}\\right)}\n\\right].\n$$\n\nFor example, the medium-coffee, high-PRS contrast under this main-effects model is\n\n$$\n\\widehat{\\ell}_{j,M,H}\n= \\widehat{\\beta}_{j,\\text{CoffeeMedium}}\n+ \\widehat{\\beta}_{j,\\text{PRSHigh}},\n$$\n\nso that\n\n$$\n\\widehat{\\operatorname{OR}}_{j,M,H}\n= \\exp\\left(\n  \\widehat{\\beta}_{j,\\text{CoffeeMedium}}\n  + \\widehat{\\beta}_{j,\\text{PRSHigh}}\n\\right).\n$$\n\nThe variance of this sum includes both coefficient variances and twice their covariance. Because this working model contains no coffee-by-PRS interaction, effects combine additively on the log-odds scale and multiplicatively on the odds scale for each outcome contrast. This is a model-based association, not a causal effect.\n\n\n::: {#tbl-pre-cof-effect .cell tbl-cap='Joint associations of PRS and coffee consumption with prediabetes/T2DM'}\n\n```{.r .cell-code}\nPRSlevels = paste0(\"PRS\", rep(levels, times = 3))\nCoflevels = paste0(\"Coffee\", rep(levels, each = 3))\n\nprs_cof_OR_table <- tibble(\n  Cof_levels = rep(levels, each = 3),\n  PRS_levels = rep(levels, times = 3),\n  Pre_prs_cof1 = map2_chr(PRSlevels, Coflevels, ~ get_OR_CI(prs_cof1_ml, \"Pre\", c(.x, .y))),\n  Pre_prs_cof2 = map2_chr(PRSlevels, Coflevels, ~ get_OR_CI(prs_cof2_ml, \"Pre\", c(.x, .y))),\n  Pre_prs_cof3 = map2_chr(PRSlevels, Coflevels, ~ get_OR_CI(prs_cof3_ml, \"Pre\", c(.x, .y))),\n  T2DM_prs_cof1 = map2_chr(PRSlevels, Coflevels, ~ get_OR_CI(prs_cof1_ml, \"T2DM\", c(.x, .y))),\n  T2DM_prs_cof2 = map2_chr(PRSlevels, Coflevels, ~ get_OR_CI(prs_cof2_ml, \"T2DM\", c(.x, .y))),\n  T2DM_prs_cof3 = map2_chr(PRSlevels, Coflevels, ~ get_OR_CI(prs_cof3_ml, \"T2DM\", c(.x, .y))))\n\ngt(prs_cof_OR_table,\n   rowname_col = \"PRS_levels\",\n   groupname_col = \"Cof_levels\", \n   row_group_as_column = TRUE) |>\n  tab_stubhead(label = c(\"Coffee\", \"PRS\")) |>\n  tab_spanner(label = \"Pre\", columns = starts_with(\"Pre\")) |>\n  tab_spanner(label = \"T2DM\", columns = starts_with(\"T2DM\")) |>\n  cols_label(ends_with(\"1\") ~ \"M1\",\n             ends_with(\"2\") ~ \"M2\",\n             ends_with(\"3\") ~ \"M3\") |>\n  fmt_markdown()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"itqsdcdghr\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#itqsdcdghr table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#itqsdcdghr thead, #itqsdcdghr tbody, #itqsdcdghr tfoot, #itqsdcdghr tr, #itqsdcdghr td, #itqsdcdghr th {\n  border-style: none;\n}\n\n#itqsdcdghr p {\n  margin: 0;\n  padding: 0;\n}\n\n#itqsdcdghr .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#itqsdcdghr .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#itqsdcdghr .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#itqsdcdghr .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#itqsdcdghr .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#itqsdcdghr .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#itqsdcdghr .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#itqsdcdghr .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#itqsdcdghr .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#itqsdcdghr .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#itqsdcdghr .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#itqsdcdghr .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#itqsdcdghr .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#itqsdcdghr .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#itqsdcdghr .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itqsdcdghr .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#itqsdcdghr .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#itqsdcdghr .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#itqsdcdghr .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itqsdcdghr .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#itqsdcdghr .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itqsdcdghr .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#itqsdcdghr .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itqsdcdghr .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#itqsdcdghr .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#itqsdcdghr .gt_left {\n  text-align: left;\n}\n\n#itqsdcdghr .gt_center {\n  text-align: center;\n}\n\n#itqsdcdghr .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#itqsdcdghr .gt_font_normal {\n  font-weight: normal;\n}\n\n#itqsdcdghr .gt_font_bold {\n  font-weight: bold;\n}\n\n#itqsdcdghr .gt_font_italic {\n  font-style: italic;\n}\n\n#itqsdcdghr .gt_super {\n  font-size: 65%;\n}\n\n#itqsdcdghr .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#itqsdcdghr .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#itqsdcdghr .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#itqsdcdghr .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#itqsdcdghr .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#itqsdcdghr .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#itqsdcdghr .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#itqsdcdghr .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#itqsdcdghr div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"2\" scope=\"colgroup\" id=\"a::stub\">Coffee</th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"Pre\">\n        <div class=\"gt_column_spanner\">Pre</div>\n      </th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"3\" scope=\"colgroup\" id=\"T2DM\">\n        <div class=\"gt_column_spanner\">T2DM</div>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_prs_cof1\">M1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_prs_cof2\">M2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pre_prs_cof3\">M3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_prs_cof1\">M1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_prs_cof2\">M2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"T2DM_prs_cof3\">M3</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr class=\"gt_row_group_first\"><td headers=\"Low stub_2_1 stub_1\" rowspan=\"3\" class=\"gt_row gt_left gt_stub_row_group\">Low</td>\n<th id=\"stub_2_1\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TG93\"><span class='gt_from_md'>Low</span></span></th>\n<td headers=\"Low stub_2_1 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"Low stub_2_1 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"Low stub_2_1 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"Low stub_2_1 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"Low stub_2_1 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td>\n<td headers=\"Low stub_2_1 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MSA8YnI+ICgxLCAxKQ==\"><span class='gt_from_md'>1 <br> (1, 1)</span></span></td></tr>\n    <tr><th id=\"stub_2_2\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TWVkaXVt\"><span class='gt_from_md'>Medium</span></span></th>\n<td headers=\"Low stub_2_2 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4zOCA8YnI+ICgxLjE1LCAxLjY1KQ==\"><span class='gt_from_md'>1.38 <br> (1.15, 1.65)</span></span></td>\n<td headers=\"Low stub_2_2 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS40IDxicj4gKDEuMjEsIDEuNjMp\"><span class='gt_from_md'>1.4 <br> (1.21, 1.63)</span></span></td>\n<td headers=\"Low stub_2_2 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4zNiA8YnI+ICgxLjE2LCAxLjU5KQ==\"><span class='gt_from_md'>1.36 <br> (1.16, 1.59)</span></span></td>\n<td headers=\"Low stub_2_2 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi40NiA8YnI+ICgyLjA1LCAyLjk0KQ==\"><span class='gt_from_md'>2.46 <br> (2.05, 2.94)</span></span></td>\n<td headers=\"Low stub_2_2 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi41NSA8YnI+ICgyLjI2LCAyLjg3KQ==\"><span class='gt_from_md'>2.55 <br> (2.26, 2.87)</span></span></td>\n<td headers=\"Low stub_2_2 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi4yOCA8YnI+ICgyLjAyLCAyLjU3KQ==\"><span class='gt_from_md'>2.28 <br> (2.02, 2.57)</span></span></td></tr>\n    <tr><th id=\"stub_2_3\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"SGlnaA==\"><span class='gt_from_md'>High</span></span></th>\n<td headers=\"Low stub_2_3 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS42NiA8YnI+ICgxLjM5LCAxLjk5KQ==\"><span class='gt_from_md'>1.66 <br> (1.39, 1.99)</span></span></td>\n<td headers=\"Low stub_2_3 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS43NCA8YnI+ICgxLjUsIDIuMDEp\"><span class='gt_from_md'>1.74 <br> (1.5, 2.01)</span></span></td>\n<td headers=\"Low stub_2_3 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS41OCA8YnI+ICgxLjM1LCAxLjg2KQ==\"><span class='gt_from_md'>1.58 <br> (1.35, 1.86)</span></span></td>\n<td headers=\"Low stub_2_3 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My43NiA8YnI+ICgzLjE1LCA0LjQ4KQ==\"><span class='gt_from_md'>3.76 <br> (3.15, 4.48)</span></span></td>\n<td headers=\"Low stub_2_3 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"NC4xOSA8YnI+ICgzLjczLCA0LjcxKQ==\"><span class='gt_from_md'>4.19 <br> (3.73, 4.71)</span></span></td>\n<td headers=\"Low stub_2_3 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My4xNiA8YnI+ICgyLjgsIDMuNTYp\"><span class='gt_from_md'>3.16 <br> (2.8, 3.56)</span></span></td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"Medium stub_2_4 stub_1\" rowspan=\"3\" class=\"gt_row gt_left gt_stub_row_group\">Medium</td>\n<th id=\"stub_2_4\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TG93\"><span class='gt_from_md'>Low</span></span></th>\n<td headers=\"Medium stub_2_4 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MSA8YnI+ICgwLjY4LCAwLjk3KQ==\"><span class='gt_from_md'>0.81 <br> (0.68, 0.97)</span></span></td>\n<td headers=\"Medium stub_2_4 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNywgMC45Mik=\"><span class='gt_from_md'>0.8 <br> (0.7, 0.92)</span></span></td>\n<td headers=\"Medium stub_2_4 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNjksIDAuOTIp\"><span class='gt_from_md'>0.8 <br> (0.69, 0.92)</span></span></td>\n<td headers=\"Medium stub_2_4 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MiA8YnI+ICgwLjcsIDAuOTcp\"><span class='gt_from_md'>0.82 <br> (0.7, 0.97)</span></span></td>\n<td headers=\"Medium stub_2_4 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MyA8YnI+ICgwLjczLCAwLjk0KQ==\"><span class='gt_from_md'>0.83 <br> (0.73, 0.94)</span></span></td>\n<td headers=\"Medium stub_2_4 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNywgMC45MSk=\"><span class='gt_from_md'>0.8 <br> (0.7, 0.91)</span></span></td></tr>\n    <tr><th id=\"stub_2_5\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TWVkaXVt\"><span class='gt_from_md'>Medium</span></span></th>\n<td headers=\"Medium stub_2_5 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4xMiA8YnI+ICgwLjg3LCAxLjQ0KQ==\"><span class='gt_from_md'>1.12 <br> (0.87, 1.44)</span></span></td>\n<td headers=\"Medium stub_2_5 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4xMyA8YnI+ICgwLjkzLCAxLjM3KQ==\"><span class='gt_from_md'>1.13 <br> (0.93, 1.37)</span></span></td>\n<td headers=\"Medium stub_2_5 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4wOCA8YnI+ICgwLjg4LCAxLjM0KQ==\"><span class='gt_from_md'>1.08 <br> (0.88, 1.34)</span></span></td>\n<td headers=\"Medium stub_2_5 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi4wMiA8YnI+ICgxLjU5LCAyLjU3KQ==\"><span class='gt_from_md'>2.02 <br> (1.59, 2.57)</span></span></td>\n<td headers=\"Medium stub_2_5 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi4xMSA8YnI+ICgxLjc4LCAyLjUxKQ==\"><span class='gt_from_md'>2.11 <br> (1.78, 2.51)</span></span></td>\n<td headers=\"Medium stub_2_5 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS44MiA8YnI+ICgxLjUyLCAyLjE3KQ==\"><span class='gt_from_md'>1.82 <br> (1.52, 2.17)</span></span></td></tr>\n    <tr><th id=\"stub_2_6\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"SGlnaA==\"><span class='gt_from_md'>High</span></span></th>\n<td headers=\"Medium stub_2_6 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4zNSA8YnI+ICgxLjA1LCAxLjczKQ==\"><span class='gt_from_md'>1.35 <br> (1.05, 1.73)</span></span></td>\n<td headers=\"Medium stub_2_6 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS40IDxicj4gKDEuMTUsIDEuNyk=\"><span class='gt_from_md'>1.4 <br> (1.15, 1.7)</span></span></td>\n<td headers=\"Medium stub_2_6 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4yNiA8YnI+ICgxLjAyLCAxLjU2KQ==\"><span class='gt_from_md'>1.26 <br> (1.02, 1.56)</span></span></td>\n<td headers=\"Medium stub_2_6 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My4wOSA8YnI+ICgyLjQ0LCAzLjkzKQ==\"><span class='gt_from_md'>3.09 <br> (2.44, 3.93)</span></span></td>\n<td headers=\"Medium stub_2_6 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My40NyA8YnI+ICgyLjkyLCA0LjEzKQ==\"><span class='gt_from_md'>3.47 <br> (2.92, 4.13)</span></span></td>\n<td headers=\"Medium stub_2_6 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi41MSA8YnI+ICgyLjEsIDMuMDEp\"><span class='gt_from_md'>2.51 <br> (2.1, 3.01)</span></span></td></tr>\n    <tr class=\"gt_row_group_first\"><td headers=\"High stub_2_7 stub_1\" rowspan=\"3\" class=\"gt_row gt_left gt_stub_row_group\">High</td>\n<th id=\"stub_2_7\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TG93\"><span class='gt_from_md'>Low</span></span></th>\n<td headers=\"High stub_2_7 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC45IDxicj4gKDAuNzUsIDEuMDgp\"><span class='gt_from_md'>0.9 <br> (0.75, 1.08)</span></span></td>\n<td headers=\"High stub_2_7 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44NSA8YnI+ICgwLjc0LCAwLjk3KQ==\"><span class='gt_from_md'>0.85 <br> (0.74, 0.97)</span></span></td>\n<td headers=\"High stub_2_7 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44MyA8YnI+ICgwLjcyLCAwLjk2KQ==\"><span class='gt_from_md'>0.83 <br> (0.72, 0.96)</span></span></td>\n<td headers=\"High stub_2_7 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC45NyA8YnI+ICgwLjgyLCAxLjE0KQ==\"><span class='gt_from_md'>0.97 <br> (0.82, 1.14)</span></span></td>\n<td headers=\"High stub_2_7 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44NyA8YnI+ICgwLjc2LCAwLjk5KQ==\"><span class='gt_from_md'>0.87 <br> (0.76, 0.99)</span></span></td>\n<td headers=\"High stub_2_7 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MC44IDxicj4gKDAuNywgMC45MSk=\"><span class='gt_from_md'>0.8 <br> (0.7, 0.91)</span></span></td></tr>\n    <tr><th id=\"stub_2_8\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"TWVkaXVt\"><span class='gt_from_md'>Medium</span></span></th>\n<td headers=\"High stub_2_8 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4yNSA8YnI+ICgwLjk3LCAxLjYp\"><span class='gt_from_md'>1.25 <br> (0.97, 1.6)</span></span></td>\n<td headers=\"High stub_2_8 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4xOSA8YnI+ICgwLjk3LCAxLjQ1KQ==\"><span class='gt_from_md'>1.19 <br> (0.97, 1.45)</span></span></td>\n<td headers=\"High stub_2_8 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4xMyA8YnI+ICgwLjkxLCAxLjM5KQ==\"><span class='gt_from_md'>1.13 <br> (0.91, 1.39)</span></span></td>\n<td headers=\"High stub_2_8 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi4zNyA8YnI+ICgxLjg3LCAzLjAyKQ==\"><span class='gt_from_md'>2.37 <br> (1.87, 3.02)</span></span></td>\n<td headers=\"High stub_2_8 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi4yMiA8YnI+ICgxLjg2LCAyLjY0KQ==\"><span class='gt_from_md'>2.22 <br> (1.86, 2.64)</span></span></td>\n<td headers=\"High stub_2_8 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS44MiA8YnI+ICgxLjUzLCAyLjE4KQ==\"><span class='gt_from_md'>1.82 <br> (1.53, 2.18)</span></span></td></tr>\n    <tr><th id=\"stub_2_9\" scope=\"row\" class=\"gt_row gt_left gt_stub\"><span data-qmd-base64=\"SGlnaA==\"><span class='gt_from_md'>High</span></span></th>\n<td headers=\"High stub_2_9 Pre_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS41IDxicj4gKDEuMTcsIDEuOTIp\"><span class='gt_from_md'>1.5 <br> (1.17, 1.92)</span></span></td>\n<td headers=\"High stub_2_9 Pre_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS40NyA8YnI+ICgxLjIxLCAxLjc5KQ==\"><span class='gt_from_md'>1.47 <br> (1.21, 1.79)</span></span></td>\n<td headers=\"High stub_2_9 Pre_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"MS4zMSA8YnI+ICgxLjA2LCAxLjYyKQ==\"><span class='gt_from_md'>1.31 <br> (1.06, 1.62)</span></span></td>\n<td headers=\"High stub_2_9 T2DM_prs_cof1\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My42MyA8YnI+ICgyLjg2LCA0LjYp\"><span class='gt_from_md'>3.63 <br> (2.86, 4.6)</span></span></td>\n<td headers=\"High stub_2_9 T2DM_prs_cof2\" class=\"gt_row gt_left\"><span data-qmd-base64=\"My42NCA8YnI+ICgzLjA3LCA0LjMyKQ==\"><span class='gt_from_md'>3.64 <br> (3.07, 4.32)</span></span></td>\n<td headers=\"High stub_2_9 T2DM_prs_cof3\" class=\"gt_row gt_left\"><span data-qmd-base64=\"Mi41MyA8YnI+ICgyLjEyLCAzLjAxKQ==\"><span class='gt_from_md'>2.53 <br> (2.12, 3.01)</span></span></td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nThese joint-category contrasts can be calculated from a single multinomial model; separate stratification of the dataset is not required for this table.\n\n# Relation to the published article\n\nThis page preserves a subset of the analyses and decisions considered during manuscript preparation. It is an analytical record rather than a reconstruction of every final analysis, and the published article is the definitive source for the study methods, results, and interpretation.\n\nSeveral features of the final analysis are important when reading this record:\n\n1. The published article reports an included sample of 7,668 and labels its main association table as $n = 7{,}668$, whereas the complete-case working models on this page use 6,224 participants. The available record does not reconcile this difference.\n2. The final article used multinomial logistic regression with NGM as the reference outcome and reported three sequential covariate-adjustment sets.\n3. Education was included in Model 1 of the published analysis. By contrast, the working candidate formulas preserved above add `Education` in the third covariate set.\n4. The final categorical coffee-by-PRS interaction was evaluated in the fully adjusted model using a likelihood-ratio test. The reported $p$ value was .21, providing no evidence of multiplicative interaction in that analysis.\n5. The published work additionally examined coffee consumption using restricted cubic splines and conducted sensitivity analyses focused on newly diagnosed diabetes and recruitment period. Those analyses are not reproduced on this page.\n\nIn the final results, medium and high coffee-consumption categories were associated with lower odds of prevalent prediabetes and T2DM, whereas higher PRS categories were associated with higher odds. The dose-response analysis suggested a potentially U-shaped association between coffee consumption and both outcomes. These cross-sectional associations should not be interpreted as evidence that coffee consumption causes a reduction in diabetes risk.\n\nFor the complete methods, results, sensitivity analyses, and interpretation, see [Rao et al. (2025), *Interaction between coffee consumption and polygenic risk score in relation to diabetes: insights from the Maastricht study*](https://doi.org/10.1007/s00394-025-03782-y).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}